### ISSUE TITLE
Allow non constant TestDriverDefaultValue

### ISSUE THREAD

**Issue by Cunibon** [bmw-tech/widget_driver#151]
**Is your feature request related to a problem? Please describe.**
While trying to move some of our widgets to WidgetDriver I noticed that the TestDriverDefaultValue has to be a constant. 
This is problematic as we use the built_value package which does not have constant constructors. For example for BuiltSet. This means I cannot use the generated code for tests.

**Describe the solution you'd like**
It would be great if we could use non constant values for tests. 
I can see this to be more or less impossible to implement though as you would need imports to a given library inside the generated code 

**Describe alternatives you've considered**
Maybe the test could fall back to the values of an actual instance of the driver in case no TestDriverDefaultValue is given. This way you might be able to get around the problem for values that are not constant while still allowing for values to be overwritten by TestDriverDefaultValue

**Comment by robert-northmind** [comment]
Hi @Cunibon,
Thanks for this feature request also. And thanks fro trying out WidgetDriver 😄 

About your issue. Just to make sure that I understand it correctly. 
You have a driver and it has a public property/method which returns something which has type `BuiltSet`.
So something like this:

```
class MyDriver extends WidgetDriver {
   ...

   BuiltSet get someSet => ...

   ...
}
```

And then above the `BuiltSet get someSet` you have issues adding the `@TestDriverDefaultValue(BuiltSet())` since the `BuiltSet` does not contain const constructors?


If this is your issue then it is a bit tricky. 

Since the TestDriver generation is using the annotations to create the test driver correctly. But in dart, the annotations does only accept const input parameters.

So this sort of gives you 3 options.

1. Return something else from the Driver. So instead of returning a `BuiltSet` then return some other type which supports const constructors.
2. Create a custom TestDriver and DriverProvider. So you don't actually need to use the code generation for all your drivers. You can also if you want create a test driver manually. Please see this readme for more info: https://github.com/bmw-tech/widget_driver/blob/master/widget_driver/doc/drivers_without_generation.md
3. You could create your own custom dart class which implements the `BuiltSet`. Then make your custom class have a const constructor. 

Here is an example of how you could create your own custom class which has a const constructor.
So image you have some non-const-class called `MyClass`:
```
class MyClass {
  final String myString;

  MyClass(this.myString);
}
```

And then you create a custom class called `ConstMyClass` and then you can make that class const:
```
class ConstMyClass implements MyClass {
  const ConstMyClass();

  @override
  String get myString {
    return "";
  }
}
```

And now you can do something like this in your driver:
```
@TestDriverDefaultValue(ConstMyClass())
  MyClass get getTheMyStuff {
    return MyClass("test");
  }
```


Does any of these suggestions help you to solve your issue?
If not then please give me some more feedback and context so that we can find some other way to solve it.

Thanks again for your feedback and suggestions 😄

**Comment by Cunibon** [comment]
Hey @robert-northmind 

I think option 2 would be the cleanest approach for me, in this case.

Thanks a lot for the feedback 😁

**Comment by robert-northmind** [comment]
So currently, due to limitations in how annotation work in dart, we can only use const values when generating TestDriver.
But as mentioned in this issue, there is a workaround where you can just define the TestDriver yourself (without using generation).
So I will close this issue.
