### ISSUE TITLE
Allow to test DriveableWidget in full context

### ISSUE THREAD

**Issue by Cunibon** [bmw-tech/widget_driver#152]
**Is your feature request related to a problem? Please describe.**
While trying to test a widget that encompasses a DrivableWidget to some extend I got the error message "'_$TestFeatureDetailsPageDriver' has no instance getter 'hasNoMap'.". While the error itself is the result of something else it highlighted a problem. You cannot test a DrivableWidget in its full context as it will always default to its TestDriver.
While looking through the code I noticed it is possible to pass "environmentInfo" to the DrivableWidget which could be used to stop the widget from defaulting to the TestDriver. This is not possible here though as the DrivableWidget is nested.

**Describe the solution you'd like**
It would be great if we could allow the DrivableWidget to use its actual implementation in the scope of a test.

**Describe alternatives you've considered**
For now I am setting:
```
environmentInfo: RuntimeEnvironmentInfo(
            platformEnvironment: PlatformEnvironment(
              getEnvironment: () => {},
            ),
          ),
```
in the constructor of my DrivableWidget as it is impossible for me to use it in tests otherwise

**Additional context**
Somewhat related to: https://github.com/bmw-tech/widget_driver/issues/151

**Comment by robert-northmind** [comment]
Hi @Cunibon,
Thanks for your feature suggestion. 

So if I understand your issue, it is that you have a drivable widget and you are not able to control the driver which is used by it when you are testing it.

If that is your issue, then actually there already is a fix for it. 
The widget_driver_test package can help you there. It offers a way to easily provide mockDrivers to your drivable widgets.
Then these mockDrivers will be used instead of the hardcoded testDrivers.

Please see the readme here: 
https://github.com/bmw-tech/widget_driver/tree/master/widget_driver_test#create-a-mock-driver

You can also check out this example widget test to see how it can be used in practice:
https://github.com/bmw-tech/widget_driver/blob/master/widget_driver/example/test/widget_tests/home_page/home_page_test.dart

Does that help solve your problem?

**Comment by robert-northmind** [comment]
And one more small note: 
I guess the reason why you are getting this error message: 
"'_$TestFeatureDetailsPageDriver' has no instance getter 'hasNoMap'."
is because in your `FeatureDetailsPageDriver` you did not mark the `hasNoMap` property with the `@TestDriverDefaultValue` annotation. 
So then when you run the generator to generate your test drivers, then it will not create a default test value for the `hasNoMap` property.

**Comment by Cunibon** [comment]
Hello @robert-northmind , thank you for the quick reply!

I know about the MockWidget injection but in this case I don't actually need the driver to be mocked, since all needed providers exist in the context anyway. So the whole widget could just function in the way it is intended without any mock.

An option to opt out of using the mockDriver for tests would be very nice for these cases.

And about the other point you mentioned this is as a result of the other ticket #151+ I opened with BuiltSet not having a const constructor, so I am not able to mock it correctly.

**Comment by robert-northmind** [comment]
Hi again @Cunibon, Okay I see. So you want a way to toggle that a DrivableWidget can use its real driver in a test?

I guess there could be 2 different ways to solve this. 

1. We could give you an option in the Driver to specify that a TestDriver is not needed for this specific driver. So that a real driver would always be used. In all tests.
2. Or we could offer some API where you could say before a specific test, that during this test you want to use real drivers.

I guess what speaks agains option 1 would be that you loose the decoupling of widget tests. 
Because image you have some DrivableWidget called `MyCoolDrivableWidget` and you say that it always should use the real driver in all its tests.
This all works good since you always make sure that all the needed dependencies are always injected in your tests.
But now some weeks later, you add the `MyCoolDrivableWidget` as a child widget in some other widget called `MyReusableWidget`.
Now suddenly, all widget tests which implicitly has the `MyReusableWidget` as a child, might start to crash. Since they didn't inject all the needed dependencies needed by the real driver in `MyCoolDrivableWidget`. 
Depending how big your widget trees are, you might have to update a lot of other widget tests now.

That is the benefit that these `TestDrivers` bring. They allow child widgets to not impact parent widgets.

So maybe option 2 would be better, that you before each test could say, that for this specific widget test, you want to use all the real child logic.

Or if you know that you really want a drivableWidget to always use the real driver. then maybe we should just allow it and go with option 1.  We would need to discuss this also with the other contributors to WidgetDriver.


But just out of interest. Why do you want to test the logic of child widgets in your parent widget tests?
One idea behind WidgetDriver is to help you test widgets in isolation. 

Imagine you have a widget tree that looks something like this:
```
                                                ParentWidget
                                              /                       \
                          Child1Widget                      Child2Widget
                            /             \
GrandChild1Widget   GrandChild2Widget
```

The idea would be that when you test `ParentWidget` then you don't care about the logic inside any of the child widgets.
For example, if `GrandChild1Widget` is a drivable widget. 
Then you don't care about the different states it might have when you are testing `ParentWidget`. 
Since in the tests for `ParentWidget`, you only care about testing that it puts `Child1Widget` and `Child2Widget` on the screen. and nothing more. You don't need to test what actually is shown inside the `Child1Widget` and `Child2Widget`.

Maybe you could explain your current situation/use case a bit more so that we better understand how to best solve your issue. Like explain why you need/want to test all real logic at once.

Thanks again for your feedback and your help in making WidgetDriver more usable 👍

**Comment by Cunibon** [comment]
I think option 2 would be the better approach.
You can already force option 1 by for example creating a class:
```
class ForceRealDriver extends RuntimeEnvironmentInfo {
  @override
  bool isRunningInTestEnvironment() => false;
}
```

and passing it in the constuctor of the "DrivableWidget" as "environmentInfo".     
Which is what I am currently doing.


About your question. In my case it is tightly coupled to my other ticket about not being able to use the generated TestDrivers.

But I can also picture a different scenario.    
Lets say you have a DriveableWidget `CharacterSelector` whoes state would normaly be managed by `CharacterSelectorProvider`.

Now lets replicate the scenario from before with an example:

```
			  CharacterManager
			/		\
	CharacterSelectorProvider	Child2Widget
		/		\
	CharacterSelector   CharacterInformation
```

When testing `CharacterManager` all dependencies of `CharacterSelector` exist in the context anyway and `CharacterSelector` plays a crucial role in the way `CharacterManager` works, as the `CharacterInformation` should update based on the selected character.    
It would be unnecessary to mock it and the defaulValues of the TestingWidget will not cover all cases. Just having the normal widget here would work just fine.

**Comment by robert-northmind** [comment]
Hi again @Cunibon,  so, finally, here is a PR which gives you the API you need to control the use of real drivers in your widget tests: https://github.com/bmw-tech/widget_driver/pull/153
Feel free to check it out and come with feedback if something is missing.

**Comment by robert-northmind** [comment]
Hey @Cunibon, So we just merged all the PRs and you should now be able to start using this.
If you need any guidance then feel free to check our this README: https://github.com/bmw-tech/widget_driver/blob/master/widget_driver_test/README.md#use-real-drivers-in-your-drivablewidgets
I think (hope) it explains pretty well how to use this new testing feature.

Or just ping us and we will try and help you
